### ISSUE TITLE
How to set float size decoration?

### ISSUE THREAD

**Issue by sfyc23** [fondesa/recycler-view-divider#203]
Sometimes the required decoration height is not an integer 。  

Can the  
```
DividerBuilder.size(size: Int, sizeUnit: Int = TypedValue.COMPLEX_UNIT_PX) 
```
be adjusted to 
```
DividerBuilder.size(size: Float, sizeUnit: Int = TypedValue.COMPLEX_UNIT_PX) 
```

**Comment by fondesa** [comment]
You can convert your floating-point height to an integer when you set the divider size.

Unfortunately, the divider size can't be a `float` because the Android's framework requires an `int` to render the divider and apply its offset so, at a certain point, this library should convert your integer to a float anyway.

In this case, it's better you do the conversion manually so it's explicit (and you can choose to truncate or round the float) instead of doing it inside of the library.

If you have other questions on this issue, don't hesitate to re-open it.

**Comment by sfyc23** [comment]
Thank you for your answer
